# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [35]:
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [36]:
print(np.__version__)

print(np.show_config())


2.1.3
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/djeny/anaconda3/Library/include
    lib directory: C:/Users/djeny/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_25aj347ekn\croot\numpy_and_numpy_base_1730835595898\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/djeny/anaconda3/Library/include
    lib directory: C:/Users/djeny/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_25aj347ekn\croot\numpy_and_numpy_base_1730835595898\_h_env\Library\lib\pkgconfig
    version: '2023.1'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30156
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30156
  cython:
    commands: cython
    linker: cython
    name: cyt

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [37]:
a = np.random.random((2,3,5))




### 4. Print a.


In [38]:
print("\nRandom a:")
print(a)



Random a:
[[[0.71998698 0.63200204 0.86816356 0.27602794 0.78084189]
  [0.86856384 0.89424912 0.80526823 0.41021395 0.96030042]
  [0.31196873 0.57661913 0.51625559 0.8798331  0.57418087]]

 [[0.0606913  0.79078802 0.3614799  0.78029271 0.1571675 ]
  [0.01726627 0.78019435 0.77617489 0.70523232 0.36284746]
  [0.82726614 0.7679948  0.45927667 0.0249543  0.12908318]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [39]:
b = np.ones((5,2,3))



### 6. Print b.


In [40]:
print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [41]:
# No, a and b they dont have the same size. 

def numpy_info(a):
        print("\nThe dimension is:", a.ndim)
        print("The shape is:", a.shape)
        print("The size is:", a.size)

def numpy_info(b):
        print("\nThe dimension is:", b.ndim)
        print("The shape is:", b.shape)
        print("The size is:", b.size)

print("\nArray Information:")
numpy_info(a)
numpy_info(b)



Array Information:

The dimension is: 3
The shape is: (2, 3, 5)
The size is: 30

The dimension is: 3
The shape is: (5, 2, 3)
The size is: 30



### 8. Are you able to add a and b? Why or why not?


In [42]:
# No, because they dont have the same size.

add_a_b = a + b
print(add_a_b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [ ]:
print(a)

[[[0.49195546 0.92371952 0.84277399 0.98147388 0.19097683]
  [0.40854871 0.89776459 0.54325255 0.20913217 0.77831776]
  [0.4252487  0.96015547 0.35666829 0.63830921 0.81320312]]

 [[0.22503355 0.84137003 0.02194315 0.04400129 0.75609736]
  [0.01083038 0.12296277 0.22541905 0.2232303  0.46367658]
  [0.72570429 0.14812373 0.34577547 0.77892227 0.30796185]]]


In [ ]:
c = b.transpose(1,2,0)
print(c)
print(" the shape is: ", c.shape)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
 the shape is:  (2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [ ]:
d = a + c
print(d)

[[[1.49195546 1.92371952 1.84277399 1.98147388 1.19097683]
  [1.40854871 1.89776459 1.54325255 1.20913217 1.77831776]
  [1.4252487  1.96015547 1.35666829 1.63830921 1.81320312]]

 [[1.22503355 1.84137003 1.02194315 1.04400129 1.75609736]
  [1.01083038 1.12296277 1.22541905 1.2232303  1.46367658]
  [1.72570429 1.14812373 1.34577547 1.77892227 1.30796185]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [ ]:

print("a =", a)
print("\n"," d =", d)

# "d" have a +1 unit value from "a" in all the values in the matrix.

a = [[[0.49195546 0.92371952 0.84277399 0.98147388 0.19097683]
  [0.40854871 0.89776459 0.54325255 0.20913217 0.77831776]
  [0.4252487  0.96015547 0.35666829 0.63830921 0.81320312]]

 [[0.22503355 0.84137003 0.02194315 0.04400129 0.75609736]
  [0.01083038 0.12296277 0.22541905 0.2232303  0.46367658]
  [0.72570429 0.14812373 0.34577547 0.77892227 0.30796185]]]

  d = [[[1.49195546 1.92371952 1.84277399 1.98147388 1.19097683]
  [1.40854871 1.89776459 1.54325255 1.20913217 1.77831776]
  [1.4252487  1.96015547 1.35666829 1.63830921 1.81320312]]

 [[1.22503355 1.84137003 1.02194315 1.04400129 1.75609736]
  [1.01083038 1.12296277 1.22541905 1.2232303  1.46367658]
  [1.72570429 1.14812373 1.34577547 1.77892227 1.30796185]]]



### 12. Multiply a and c. Assign the result to e.


In [ ]:
e = a * c
e


array([[[0.49195546, 0.92371952, 0.84277399, 0.98147388, 0.19097683],
        [0.40854871, 0.89776459, 0.54325255, 0.20913217, 0.77831776],
        [0.4252487 , 0.96015547, 0.35666829, 0.63830921, 0.81320312]],

       [[0.22503355, 0.84137003, 0.02194315, 0.04400129, 0.75609736],
        [0.01083038, 0.12296277, 0.22541905, 0.2232303 , 0.46367658],
        [0.72570429, 0.14812373, 0.34577547, 0.77892227, 0.30796185]]])



### 13. Does e equal to a? Why or why not?


In [ ]:
e == a

# yes, if we do the equality comparison we can see that is true.


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [ ]:

d_max = pd.max(d); print("the max is:", d_max)
d_min = pd.min(d); print("the min is:", d_min)
d_mean = pd.mean(d); print("the mean is:", d_mean)

the max is: 1.9814738843477686
the min is: 1.0108303765397628
the mean is: 1.490085076548622



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [ ]:
f = np.empty(shape = [2,3,5])
f


array([[[0.49195546, 0.92371952, 0.84277399, 0.98147388, 0.19097683],
        [0.40854871, 0.89776459, 0.54325255, 0.20913217, 0.77831776],
        [0.4252487 , 0.96015547, 0.35666829, 0.63830921, 0.81320312]],

       [[0.22503355, 0.84137003, 0.02194315, 0.04400129, 0.75609736],
        [0.01083038, 0.12296277, 0.22541905, 0.2232303 , 0.46367658],
        [0.72570429, 0.14812373, 0.34577547, 0.77892227, 0.30796185]]])




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [ ]:
for z in range(d.shape[0]):
    for y in range(d.shape[1]):
        for x in range(d.shape[2]):
            if d_min == d[z,y,x]:
                f[z,y,x] = 0
            elif d[z,y,x] > d_min and d[z,y,x] < d_mean:
                f[z,y,x] = 25
            elif d[z,y,x] == d_mean:
                f[z,y,x] = 50
            elif d[z,y,x] > d_mean and d[z,y,x] < d_max:
                f[z,y,x] = 75
            elif d[z,y,x] == d_max:
                f[z,y,x] = 100

print(f)

# [z,y,x] - z - depth, y - row, x - colunas
# o ciclo for corre dentro do range

[[[ 75.  75.  75. 100.  25.]
  [ 25.  75.  75.  25.  75.]
  [ 25.  75.  25.  75.  75.]]

 [[ 25.  75.  25.  25.  75.]
  [  0.  25.  25.  25.  25.]
  [ 75.  25.  25.  75.  25.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:

array(
        
        [[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:

array(
        
        [[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [ ]:
print(d)

print("\n", f)


[[[1.49195546 1.92371952 1.84277399 1.98147388 1.19097683]
  [1.40854871 1.89776459 1.54325255 1.20913217 1.77831776]
  [1.4252487  1.96015547 1.35666829 1.63830921 1.81320312]]

 [[1.22503355 1.84137003 1.02194315 1.04400129 1.75609736]
  [1.01083038 1.12296277 1.22541905 1.2232303  1.46367658]
  [1.72570429 1.14812373 1.34577547 1.77892227 1.30796185]]]

 [[[ 75.  75.  75. 100.  25.]
  [ 25.  75.  75.  25.  75.]
  [ 25.  75.  25.  75.  75.]]

 [[ 25.  75.  25.  25.  75.]
  [  0.  25.  25.  25.  25.]
  [ 75.  25.  25.  75.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [ ]:
j = np.empty((2,3,5), dtype = ("str") )

for z in range(d.shape[0]):
    for y in range(d.shape[1]):
        for x in range(d.shape[2]):
            if d_min == d[z,y,x]:
                j[z,y,x] = "A"
            elif d[z,y,x] > d_min and d[z,y,x] < d_mean:
                j[z,y,x] = "B"
            elif d[z,y,x] == d_mean:
                j[z,y,x] = "C"
            elif d[z,y,x] > d_mean and d[z,y,x] < d_max:
                j[z,y,x] = "D"
            elif d[z,y,x] == d_max:
                j[z,y,x] = "E"

print(j)

[[['D' 'D' 'D' 'E' 'B']
  ['B' 'D' 'D' 'B' 'D']
  ['B' 'D' 'B' 'D' 'D']]

 [['B' 'D' 'B' 'B' 'D']
  ['A' 'B' 'B' 'B' 'B']
  ['D' 'B' 'B' 'D' 'B']]]
